PREFIX c:<http://s.opencalais.com/1/pred/>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
	
	SELECT ?name ?shortname ?ticker ?type
	WHERE { 
		?subject rdf:type ?type .
		?subject c:name ?name .
		?subject c:shortname ?shortname .
		?subject c:ticker ?ticker .
		FILTER regex(str(?type), "^http://s.opencalais.com/1/type/er/Company*") . 
	}